language: python
os:
- linux
python:
- '3.2'
- '3.3'
- '3.4'
- 'nightly'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq
- pip install --upgrade setuptools
- pip install --upgrade pip
install:
- pip install .
script:
- python ./tests/tests.py
